FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD sample-project .jar /opt/sample-project /
EXPOSE 8080
WORKDIR /opt/sample-project /
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "sample-project .jar"]
